name = "castor-prueba-tecnica"
compatibility_date = "2024-01-01"

[env.production]
name = "castor-prueba-tecnica"

[env.production.vars]
NODE_ENV = "production"

[[env.production.kv_namespaces]]
binding = "DB"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id" 